### ISSUE TITLE
Proto without 802.11ad VLANs

### ISSUE THREAD

**Issue by gabri94** [libre-mesh/lime-packages#17]
As describing in #16, when u try to create an olsr configuration without using any vlan (olsr:0) the network device is not created.

For example if i declare the network as
<code>
config net port5
    option linux_name 'wlan0_adhoc'
    list protocols 'olsr:0'                                               
</code>

When i generate the uci config with lime-config, wlan0_adhoc is not declared in /etc/config/network

How should i use a routing protocol without any vlan?

**Comment by G10h4ck** [comment]
I would expect lime.proto.adhoc to create the base openwrt interface for wlan0_adhoc, but I am not sure if something similar happen also for plain Ethernet interface...
No time for further analysis right now, merge requests are welcome

**Comment by ilario** [comment]
With help from Gio, I started to address the problem [here](/ilario/lime-packages/compare/sandbox/olsr-without-vlan).
Does the olsr6 also need an IP on the interface for running?

We planned to solve this problem in a routing protocol independent way using macvlan, in the future.

**Comment by G10h4ck** [comment]
I have created an helper function to create macvlan without knowing the details or doing copy paste of code, take a look at this branch that is not tested yet

https://github.com/libre-mesh/lime-packages/tree/sandbox/macvlan

**Comment by gabri94** [comment]
How macvlan is going to solve this bug?
We would like to use LiMe in a legacy WCN with heterogeneous operating systems, so without any vlan on the 802.11 side.

**Comment by G10h4ck** [comment]
macvlan doesn't tag or alter packets so is compatible with other OS, btw unnamed_search_motor is your friend

**Comment by ilario** [comment]
looks that this issue is being addressed in branch vlanzero, check it out [here](/libre-mesh/lime-packages/commits/sandbox/vlanzero)

**Comment by G10h4ck** [comment]
fixed in fae59eda7464ccfd8a0a806295084ccb11485e82
