### ISSUE TITLE
libremap confif

### ISSUE THREAD

**Issue by trizonelabs** [libre-mesh/lime-packages#29]
libremap-agent-openwrt/libremap-agent/files/etc/uci-defaults/ is setting a /etc/config/libremap file if there is none existing, alas the config file is generated by libre-map though /files/config/libremap with different uci parameters.

is there a reason for libre-mesh having his own config/libremap ?

please someone should have an eye on this because it seems to generates some problems setting our own parameters via scripts.

**Comment by G10h4ck** [comment]
Yes it is the expected behaviour, libremap-agent is firmware agnostic so libre-mesh create a more specific configuration that fits better in LiMe

**Comment by ilario** [comment]
So? Is this still an issue?
