### ISSUE TITLE
IPv4 autoconfiguration can have invalid result depending on MAC address

### ISSUE THREAD

**Issue by ilario** [libre-mesh/lime-packages#34]
On my tl-wrd3600 (MAC addresses: c0:4a:00:dd:68:00-02) I set the main_ipv4_address option to 10.37.0.0/16/22 and the resulting IPv4 on br-lan interface is 10.37.0.0 which is indeed the address of the network. 
It is not a problem of the autoconfiguration mechanism, I checked that everything is ok, anyway a 0.0.0.0 is added as a perturbation to the given IPv4, just very bad luck with the MAC address of my device.
On the clients, using a DHCP client I don't get a default route and if I set this by hand it is not accepted.

    # ip r a default via 10.37.0.0
    RTNETLINK answers: Invalid argument

Thanks,
Ilario

**Comment by trizonelabs** [comment]
same problem goes for mac .... :ff ->x.x.x.255 ->broadcast
i used decr if 255 and inc if 0
but this is a general problem with ip derrived from mac 
->http://betterexplained.com/articles/understanding-the-birthday-paradox/
