### ISSUE TITLE
Dead lock in lime-config

### ISSUE THREAD

**Issue by p4u** [libre-mesh/lime-packages#4]
If "lime-config" fails, the lock file "/var/run/lime-config.pid" is never removed, so lime-config is not executable anymore until a new reboot or a manual deletion of the file.

Possible solution 1: control lua exceptions and remove lock file once an exception has occurred 

Possible solution 2: remove the lock file mechanism, is it really needed?

**Comment by G10h4ck** [comment]
Addressed in a75e972f14297d7563aa01cf538dc0e9f5eea951

> Possible solution 2: remove the lock file mechanism, is it really needed?

It is needed because hotplug can run lime-config multiple times if an usb radio is attacched
