### ISSUE TITLE
watchping on bridge

### ISSUE THREAD

**Issue by trizonelabs** [libre-mesh/lime-packages#43]
### flaw [init.d/watchping]:
if  wan-bridge is down then **/etc/init.d/watchping** selects bridge-member-interface(**eth1**) instead of bridge name (**br-wan**)  to pass as interface parameter to watchping , which obvioulsy cant be used for ping.
### outcome :
   watchping never detects internet ...a.s.o
### solution :  
   use other means of detecting the interface if a bridge involved

**Comment by p4u** [comment]
I would review and accept a pull-request related this issue.

**Comment by p4u** [comment]
Will be solved on #66
