### ISSUE TITLE
Document how the team connects

### ISSUE THREAD

**Issue by nicopace** [libre-mesh/lime-packages#45]
IRC, mailing list at least. Thanks!

**Comment by ilario** [comment]
Hi! On the [website](http://libre-mesh.org/contact.html) there is this information.
Could you specify where should we add this information also?

**Comment by nicopace** [comment]
On the readme would be great, so potential contributors can contribute easily :)

**Comment by ilario** [comment]
I filed a similar issue on lime-build, [here](/libre-mesh/lime-build/issues/6).
@devs, this issue can be closed...
