### ISSUE TITLE
Ebtables/IPtables without firewall application

### ISSUE THREAD

**Issue by p4u** [libre-mesh/lime-packages#5]
If the openwrt firewall application is not installed, ebtable rules are not properly executed. An autonomous system application not firewall dependent is needed to control ebtables/iptables.

**Comment by ilario** [comment]
Considering the use of *lime-proto-wan* in absence of OpenWRT firewall application, there is still need to manually write rules for masquerading, right? 
Should this re-open this issue?

**Comment by ilario** [comment]
What I mean is something like [this](https://github.com/libre-mesh/lime-packages/blob/0a29a26894ffb73366bc6d6d2b1e8a3d85e54b24/packages/bmx6-auto-gw-mode/files/etc/watchping/wan-ok.d/bmx6-gw#L10).

**Comment by altergui** [comment]
p4u, dear, 
loving your coding as always, and every commit signed by you is greatly appreciated :)

but could we please not have (again!) a "lime-init" thing? :P

i was happy i killed it with
https://github.com/libre-mesh/lime-packages/commit/854c93744e

and even offered an explanation on
https://github.com/libre-mesh/lime-packages/commit/f65c4d6ea7

"[lime-init is] unused and unnecesarily duplicates /etc/init.d/ functionality
if in doubt, check for example /etc/init.d/done that's really minimal (and actually is in charge of running /etc/rc.local as a monolithic hook). Anything that would go in /etc/rc.local.d/* can be implemented with just a few more lines as an /etc/init.d script, keeping LiMe closer to upstream architecture."

so i'd vote to turn this (reincarnation of) lime-init into a specific /etc/init.d/firewall-user, that only runs "sh /etc/firewall.user" at start.

that's what /etc/init.d/ is there for, after all ;)

if no-one else steps up with this, i can do it on my next coding iteration

**Comment by ilario** [comment]
Referring to my previous comment, I included some code from bmx6-auto-gw-mode in batman-adv-auto-gw-mode, [here](https://github.com/libre-mesh/lime-packages/pull/20) you are the pull request.

**Comment by p4u** [comment]
Are we in a loop? How is this issue now?

**Comment by trizonelabs** [comment]
ebtables : please could someone give me a hint why this was introduced and where this is used ?

**Comment by p4u** [comment]
Check this http://wiki.libre-mesh.org/doku.php/net_architecture

An look for "ebtables".

On 15/03/16 11:38, trizonelabs wrote:
> ebtables : please could someone give me a hint why this was introduced and where this is used ?
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/libre-mesh/lime-packages/issues/5#issuecomment-196760552
> 

-- 
./p4u

**Comment by p4u** [comment]
So, if firewall is not enabled ebtables rules are not applied. This ends up in a very strange behavior. 

So commit  dcc5d5ef44dcf11e0f9e42808fa195164a91d00e fixes this. If there is a better option than including a init script, then I would like to know.
