### ISSUE TITLE
apply-eb-ip-rules-if-not-fw.sh doesn't seem to execute any file inside firewall.user.d

### ISSUE THREAD

**Issue by egon0** [libre-mesh/lime-packages#57]
apply-eb-ip-rules-if-not-fw.sh doesn't seem to work (for me). i have replaced 

```sh /etc/firewall.user.d/*```

with

```
for file in /etc/firewall.user.d/*
  do
    sh "$file"
  done
```

and everything works as expected.

**Comment by p4u** [comment]
You are right.

If you send the correct pull-request I'll accept it.

Thanks.

**Comment by p4u** [comment]
Done. Thanks.
